Feature/inbox test
oaplatform/oap-mail pull request #4
Opened 2022-01-13 13:46 UTC by Crosby98

2022-01-13 13:51 UTC, RubikOM commented on oap-mail/src/main/java/oap/mail/test/MailBoxUtils.java
> +                    throw new RuntimeException( e );
plz specify an exception and add logic

2022-01-13 13:51 UTC, RubikOM commented on oap-mail/src/main/java/oap/mail/test/MailBoxUtils.java
> +            throw new RuntimeException( e );
same here

2022-01-13 13:52 UTC, RubikOM commented on oap-mail/src/main/java/oap/mail/test/MailBoxUtils.java
> +            // get last sent message
Do we really need this comment?

2022-01-13 13:53 UTC, RubikOM commented on oap-mail/src/main/java/oap/mail/test/MailBoxUtils.java
> +        Message message;
You can return the message straight away, no need to define it here and return in the end.

2022-01-13 14:52 UTC, vovakyrychenko requested changes

2022-01-13 14:52 UTC, vovakyrychenko commented on pom.xml
> +        <javax.mail>1.6.2</javax.mail>
here is a javax.mail already included via  oap.deps.javax.mail.version
need to update version and use that property for version

2022-01-13 14:52 UTC, vovakyrychenko commented on oap-mail/src/test/java/oap/mail/TestGMail.java
> +            assertThatMessageSentInTheBox( authenticator.username, authenticator.password )
rename  assertThatMessageSentInTheBox to simple assertInbox

2022-01-13 14:52 UTC, vovakyrychenko commented on oap-mail/src/main/java/oap/mail/test/MailBoxUtils.java
> +        } catch( Exception e ) {
use lombock @SneakyThrows insted of catching Exception and rethrowing runtime

2022-01-13 14:52 UTC, vovakyrychenko commented on pom.xml
> +        <javax.mail>1.6.2</javax.mail>
Increment 3rd digit of oap-mail.project.version.

2022-01-13 14:52 UTC, vovakyrychenko commented on oap-mail/src/main/java/oap/mail/test/MailBoxUtils.java
> +public class MailBoxUtils {
Rename it to Mailbox as per current [coding guidelines](https://app.nuclino.com/Xenoss/Engeneering/Coding-guidelines-0176b90d-0b3b-45ee-ac4b-5ef7c69f8142) we avoid using 'tool' suffixes.

2022-01-13 14:59 UTC, vovakyrychenko requested changes

2022-01-13 14:59 UTC, vovakyrychenko commented on oap-mail/src/main/java/oap/mail/MailAddress.java
> +        } else return Stream.of( addresses ).map( MailAddress::of ).collect( toList() );
There is a direct toList method in Stream in the latest java.

2022-01-13 14:59 UTC, vovakyrychenko commented on oap-mail/src/main/java/oap/mail/test/MailBoxUtils.java
> +            return convertMessage( inboxMessage );
inline variable and @SneakyThrows

2022-01-13 14:59 UTC, vovakyrychenko commented on oap-mail/src/main/java/oap/mail/test/MailBoxUtils.java
> +
This could be rewritten using Streams like

Stream.of(messages). sorted(Comparator.comparing).map(convertMEssage).toList

2022-01-13 14:59 UTC, vovakyrychenko commented on oap-mail/src/main/java/oap/mail/test/MailBoxUtils.java
> +
And @SneakyThrows

2022-01-13 14:59 UTC, vovakyrychenko commented on oap-mail/src/main/java/oap/mail/test/MailBoxUtils.java
> +        } catch( MessagingException e ) {
@SneakyThrows

2022-01-13 14:59 UTC, vovakyrychenko commented on oap-mail/src/main/java/oap/mail/test/MessageAssertion.java
> +        inbox.close();
Folder is AutoClosable, use try(....)

2022-01-13 14:59 UTC, vovakyrychenko commented on oap-mail/src/main/java/oap/mail/test/MessagesAssertion.java
> +        Folder inbox = MailBoxUtils.connectToInbox( user, password );
inline, inline

2022-01-13 14:59 UTC, vovakyrychenko commented on oap-mail/src/main/java/oap/mail/test/MessagesAssertion.java
> +        Folder inbox = MailBoxUtils.connectToInbox( user, password );
there should be inbox closing line in previous one

2022-01-13 15:58 UTC, vovakyrychenko requested changes

2022-01-13 15:58 UTC, vovakyrychenko commented on oap-mail/pom.xml
> +        <dependency>
does it conflict with javax.mail/mail dependancy?

2022-01-13 16:22 UTC, vovakyrychenko commented on oap-mail/src/main/java/oap/mail/MailAddress.java
> +            for( InternetAddress address : addresses )
Very old code, from before streams era:)

2022-01-14 15:34 UTC, vovakyrychenko commented on pom.xml
> +        <javax.mail>1.6.2</javax.mail>
Upgrade to the latest

2022-01-14 17:16 UTC, merged